version: "3.9"
services:
  mysql:
    container_name: "mysql"
    build:
      context: ./mysql
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  rabbitmq:
    container_name: "rabbitmq"
    build:
      context: ./rabbitmq
      args:
        - RABBITMQ_USER=${RABBITMQ_USER}
        - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"

  redis:
    container_name: "redis"
    build:
      context: ./redis
    ports:
      - "${REDIS_PORT}:6379"